name: Docker Build and Push

on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Generate Docker tags
        id: tag
        run: echo ::set-output name=DOCKER_TAG::$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ickyramer/Repositories/project4-5:${{ steps.tag.outputs.DOCKER_TAG }}
            ickyramer/Repositories/project4-5:latest

        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
